# fly.toml app configuration file generated for apsit-aiml on 2023-07-17T00:08:45+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apsit-aiml"
primary_region = "lax"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
